version: "3.1"

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fin_api
      POSTGRES_PASSWORD: docker
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
